### ISSUE TITLE
Add support for torque maps

### ISSUE THREAD

**Issue by andrewbt** [CartoDB/labs-cdbfiddle#1]
With a torque viz.json, cdbfiddle isn't able to parse out the sql/cartocss and fails to load.

Steps to remediate
- [ ] Fix https://github.com/CartoDB/labs-cdbfiddle/blob/master/index.html#L114 in a way that it tries to access what it currently tries (for regular non-torques), and then if it fails, tries in another way to get a torque which might be `layers[1].options.query` and `layers[1].options.tile_style`
- [ ] Since the "query" will be a special torque one and have the `_cdb_wrap`, maybe some intelligent way to parse that for displaying the _actual_ , user typed SQL in the sidebar.

**Comment by chriswhong** [comment]
Fixed in https://github.com/CartoDB/labs-cdbfiddle/commit/194ae00382ed716d0e57c50e634aeecb7f0af59d
